[2025-10-08T22:48:45.287+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG_completo.pinecone_upsert_op manual__2025-10-07T22:42:20+00:00 [queued]>
[2025-10-08T22:48:45.291+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG_completo.pinecone_upsert_op manual__2025-10-07T22:42:20+00:00 [queued]>
[2025-10-08T22:48:45.291+0000] {taskinstance.py:1359} INFO - Starting attempt 5 of 5
[2025-10-08T22:48:45.296+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): pinecone_upsert_op> on 2025-10-07 22:42:20+00:00
[2025-10-08T22:48:45.302+0000] {standard_task_runner.py:57} INFO - Started process 65732 to run task
[2025-10-08T22:48:45.305+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG_completo', 'pinecone_upsert_op', 'manual__2025-10-07T22:42:20+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/Ingestion_pipeline.py', '--cfg-path', '/tmp/tmp4aup5zms']
[2025-10-08T22:48:45.308+0000] {standard_task_runner.py:85} INFO - Job 353: Subtask pinecone_upsert_op
[2025-10-08T22:48:45.331+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG_completo.pinecone_upsert_op manual__2025-10-07T22:42:20+00:00 [running]> on host 5586102090b0
[2025-10-08T22:48:45.363+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG_completo' AIRFLOW_CTX_TASK_ID='pinecone_upsert_op' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T22:42:20+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-07T22:42:20+00:00'
[2025-10-08T22:48:45.364+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-08T22:48:45.365+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-08T22:48:45.365+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-08T22:48:45.365+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-08T22:48:45.365+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-08T22:48:45.519+0000] {logging_mixin.py:151} INFO - [PC/OP] ndjson_files=6 prefix=rag/chunks_op/2025/
[2025-10-08T22:48:45.520+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-08T22:48:45.520+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-08T22:48:45.734+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-08T22:48:45.734+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-08T22:48:45.777+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-08T22:48:45.778+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-08T22:48:45.818+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-08T22:48:45.819+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-08T22:48:45.863+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-08T22:48:45.864+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-08T22:48:45.906+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-08T22:48:45.906+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-08T22:48:45.948+0000] {logging_mixin.py:151} INFO - [PC/OP] parsed_kept=802 (tras min_chars>=20)
[2025-10-08T22:48:45.949+0000] {SentenceTransformer.py:208} INFO - Use pytorch device_name: cpu
[2025-10-08T22:48:45.949+0000] {SentenceTransformer.py:216} INFO - Load pretrained SentenceTransformer: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
[2025-10-08T22:49:05.227+0000] {logging_mixin.py:151} INFO - [PC/OP] embedding model=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 dim=384 total_vectors=802
[2025-10-08T22:49:05.231+0000] {discover_namespace_packages.py:12} INFO - Discovering subpackages in _NamespacePath(['/home/***/.local/lib/python3.8/site-packages/pinecone_plugins'])
[2025-10-08T22:49:05.231+0000] {discover_plugins.py:9} INFO - Looking for plugins in pinecone_plugins.inference
[2025-10-08T22:49:05.241+0000] {installation.py:10} INFO - Installing plugin inference into Pinecone
[2025-10-08T22:49:06.514+0000] {discover_namespace_packages.py:12} INFO - Discovering subpackages in _NamespacePath(['/home/***/.local/lib/python3.8/site-packages/pinecone_plugins'])
[2025-10-08T22:49:06.517+0000] {discover_plugins.py:9} INFO - Looking for plugins in pinecone_plugins.inference
[2025-10-08T22:49:06.519+0000] {installation.py:10} INFO - Installing plugin inference into Pinecone
[2025-10-08T22:49:14.895+0000] {logging_mixin.py:151} INFO - ✅ Upsert Pinecone (OP): indexed=802, dim=384, ns=2025
[2025-10-08T22:49:14.898+0000] {logging_mixin.py:151} INFO - ✅ Upsert Pinecone (OP): {'indexed': 802, 'dim': 384, 'namespace': '2025'}
[2025-10-08T22:49:14.898+0000] {python.py:194} INFO - Done. Returned value was: {'indexed': 802, 'dim': 384, 'namespace': '2025'}
[2025-10-08T22:49:14.918+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flujo_RAG_completo, task_id=pinecone_upsert_op, execution_date=20251007T224220, start_date=20251008T224845, end_date=20251008T224914
[2025-10-08T22:49:14.993+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-08T22:49:15.005+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
