[2025-10-01T13:49:05.729+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.eval_bm25 manual__2025-10-01T13:33:42.656094+00:00 [queued]>
[2025-10-01T13:49:05.734+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.eval_bm25 manual__2025-10-01T13:33:42.656094+00:00 [queued]>
[2025-10-01T13:49:05.734+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-10-01T13:49:05.739+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): eval_bm25> on 2025-10-01 13:33:42.656094+00:00
[2025-10-01T13:49:05.743+0000] {standard_task_runner.py:57} INFO - Started process 2557 to run task
[2025-10-01T13:49:05.745+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'eval_bm25', 'manual__2025-10-01T13:33:42.656094+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmpyte3vdri']
[2025-10-01T13:49:05.747+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask eval_bm25
[2025-10-01T13:49:05.770+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.eval_bm25 manual__2025-10-01T13:33:42.656094+00:00 [running]> on host b23249bdd303
[2025-10-01T13:49:05.804+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG' AIRFLOW_CTX_TASK_ID='eval_bm25' AIRFLOW_CTX_EXECUTION_DATE='2025-10-01T13:33:42.656094+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-01T13:33:42.656094+00:00'
[2025-10-01T13:49:05.805+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-01T13:49:05.806+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T13:49:05.806+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-01T13:49:05.807+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T13:49:05.807+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-01T13:49:05.999+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/tasks/eval_bm25_task.py", line 50, in task_eval_bm25
    if not exists(bucket_name, qrels_key, aws_conn_id):
NameError: name 'exists' is not defined
[2025-10-01T13:49:06.005+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG, task_id=eval_bm25, execution_date=20251001T133342, start_date=20251001T134905, end_date=20251001T134906
[2025-10-01T13:49:06.010+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 59 for task eval_bm25 (name 'exists' is not defined; 2557)
[2025-10-01T13:49:06.040+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-01T13:49:06.049+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
