[2025-09-30T14:48:46.596+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.listar_boletines_minio manual__2025-09-30T14:48:12.316508+00:00 [queued]>
[2025-09-30T14:48:46.601+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.listar_boletines_minio manual__2025-09-30T14:48:12.316508+00:00 [queued]>
[2025-09-30T14:48:46.601+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-09-30T14:48:46.607+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): listar_boletines_minio> on 2025-09-30 14:48:12.316508+00:00
[2025-09-30T14:48:46.611+0000] {standard_task_runner.py:57} INFO - Started process 785 to run task
[2025-09-30T14:48:46.613+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'listar_boletines_minio', 'manual__2025-09-30T14:48:12.316508+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmpdqgxhy8s']
[2025-09-30T14:48:46.615+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask listar_boletines_minio
[2025-09-30T14:48:46.642+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.listar_boletines_minio manual__2025-09-30T14:48:12.316508+00:00 [running]> on host 536168cd08ce
[2025-09-30T14:48:46.675+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG' AIRFLOW_CTX_TASK_ID='listar_boletines_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-09-30T14:48:12.316508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-30T14:48:12.316508+00:00'
[2025-09-30T14:48:46.677+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-09-30T14:48:46.678+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-09-30T14:48:46.678+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-09-30T14:48:46.678+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-09-30T14:48:46.678+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-09-30T14:48:46.946+0000] {logging_mixin.py:151} INFO - üóÇÔ∏è Listado de PDFs en s3://respaldo2/boletines/2025/:
[2025-09-30T14:48:46.946+0000] {s3.py:1361} INFO - This function shadows the 'download_file' method of S3 API, but it is not the same. If you want to use the original method from S3 API, please call 'S3Hook.get_conn().download_file()'
[2025-09-30T14:48:46.946+0000] {s3.py:1367} INFO - Downloading source S3 file from Bucket respaldo2 with path boletines/2025/22032_2025-09-16.pdf
[2025-09-30T14:48:46.989+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/tasks/procesamiento_utils.py", line 70, in leer_y_loguear_minio
    hook.download_file(key=key, bucket_name=bucket_name, local_path=local_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 138, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 92, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1393, in download_file
    file = NamedTemporaryFile(dir=local_path, prefix="airflow_tmp_", delete=False)  # type: ignore
  File "/usr/local/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpojboeesg/22032_2025-09-16.pdf/airflow_tmp_sf0zpd1l'
[2025-09-30T14:48:46.993+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG, task_id=listar_boletines_minio, execution_date=20250930T144812, start_date=20250930T144846, end_date=20250930T144846
[2025-09-30T14:48:46.997+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task listar_boletines_minio ([Errno 2] No such file or directory: '/tmp/tmpojboeesg/22032_2025-09-16.pdf/airflow_tmp_sf0zpd1l'; 785)
[2025-09-30T14:48:47.010+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-30T14:48:47.018+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
