[2025-10-05T23:20:34.724+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.guardrail_chunks manual__2025-10-05T23:14:22+00:00 [queued]>
[2025-10-05T23:20:34.731+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.guardrail_chunks manual__2025-10-05T23:14:22+00:00 [queued]>
[2025-10-05T23:20:34.732+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-05T23:20:34.738+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): guardrail_chunks> on 2025-10-05 23:14:22+00:00
[2025-10-05T23:20:34.746+0000] {standard_task_runner.py:57} INFO - Started process 3438 to run task
[2025-10-05T23:20:34.750+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'guardrail_chunks', 'manual__2025-10-05T23:14:22+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmpezfr9zot']
[2025-10-05T23:20:34.753+0000] {standard_task_runner.py:85} INFO - Job 197: Subtask guardrail_chunks
[2025-10-05T23:20:34.787+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.guardrail_chunks manual__2025-10-05T23:14:22+00:00 [running]> on host c16a2a509134
[2025-10-05T23:20:34.838+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG' AIRFLOW_CTX_TASK_ID='guardrail_chunks' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T23:14:22+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-05T23:14:22+00:00'
[2025-10-05T23:20:34.840+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-05T23:20:34.841+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:34.841+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-05T23:20:34.842+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:34.842+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-05T23:20:35.002+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:35.003+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:36.798+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:20:36.799+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 77143 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:20:36.805+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:36.805+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:36.855+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/1 → s3://respaldo2/rag/chunks_curated/2025/22032_2025-09-16.ndjson
[2025-10-05T23:20:36.856+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:36.857+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:38.080+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:20:38.082+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 77112 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:20:38.092+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:38.093+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:38.164+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/2 → s3://respaldo2/rag/chunks_curated/2025/22033_2025-09-17.ndjson
[2025-10-05T23:20:38.164+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:38.165+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:39.772+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:20:39.775+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 83477 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:20:39.793+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:39.793+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:39.855+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/3 → s3://respaldo2/rag/chunks_curated/2025/22034_2025-09-18.ndjson
[2025-10-05T23:20:39.855+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:39.856+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:41.274+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:20:41.276+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 79740 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:20:41.287+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:41.288+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:41.348+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/4 → s3://respaldo2/rag/chunks_curated/2025/22035_2025-09-19.ndjson
[2025-10-05T23:20:41.348+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:41.349+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:42.568+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:20:42.571+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 78248 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:20:42.585+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:42.586+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:42.638+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/5 → s3://respaldo2/rag/chunks_curated/2025/22036_2025-09-22.ndjson
[2025-10-05T23:20:42.639+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:42.639+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:43.943+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:20:43.947+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 5.794000 seconds
[2025-10-05T23:20:50.990+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:20:50.996+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 77083 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:20:51.013+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:51.014+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:51.106+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/6 → s3://respaldo2/rag/chunks_curated/2025/22037_2025-09-23.ndjson
[2025-10-05T23:20:51.107+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:51.107+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:52.020+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:20:52.021+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 6.918000 seconds
[2025-10-05T23:20:59.792+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:20:59.793+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 60866 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:20:59.800+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:59.801+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:20:59.851+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/7 → s3://respaldo2/rag/chunks_curated/2025/22038_2025-09-24.ndjson
[2025-10-05T23:20:59.852+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:20:59.853+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:01.216+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:21:01.219+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 10.671000 seconds
[2025-10-05T23:21:13.125+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:21:13.127+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 83525 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:21:13.132+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:13.133+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:13.179+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/8 → s3://respaldo2/rag/chunks_curated/2025/22039_2025-09-25.ndjson
[2025-10-05T23:21:13.179+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:13.180+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:14.424+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:21:14.424+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 70977 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:21:14.430+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:14.430+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:14.488+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/9 → s3://respaldo2/rag/chunks_curated/2025/22040_2025-09-26.ndjson
[2025-10-05T23:21:14.489+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:14.489+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:15.794+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:21:15.796+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 14.569000 seconds
[2025-10-05T23:21:31.547+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:21:31.549+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 5.935000 seconds
[2025-10-05T23:21:38.883+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:21:38.886+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 93035 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:21:38.908+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:38.909+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:38.978+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/10 → s3://respaldo2/rag/chunks_curated/2025/22041_2025-09-29.ndjson
[2025-10-05T23:21:38.978+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:38.979+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:40.022+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:21:40.022+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 8.987000 seconds
[2025-10-05T23:21:50.172+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:21:50.174+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 75145 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:21:50.186+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:50.187+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:50.585+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/11 → s3://respaldo2/rag/chunks_curated/2025/22042_2025-09-30.ndjson
[2025-10-05T23:21:50.586+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:21:50.586+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:21:51.710+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:21:51.712+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 12.724000 seconds
[2025-10-05T23:22:06.027+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:22:06.030+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 98427 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:22:06.039+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:22:06.040+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:22:06.094+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/12 → s3://respaldo2/rag/chunks_curated/2025/22043_2025-10-01.ndjson
[2025-10-05T23:22:06.095+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:22:06.095+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:22:07.993+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-10-05T23:22:07.994+0000] {_base_client.py:1071} INFO - Retrying request to /chat/completions in 10.349000 seconds
[2025-10-05T23:22:19.586+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:22:19.592+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 90065 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:22:19.610+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:22:19.612+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:22:19.676+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/13 → s3://respaldo2/rag/chunks_curated/2025/22044_2025-10-02.ndjson
[2025-10-05T23:22:19.677+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:22:19.677+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:22:21.019+0000] {_client.py:1025} INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
[2025-10-05T23:22:21.022+0000] {logging_mixin.py:151} INFO - ⚠️ Error LLM guardrail: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, your messages resulted in 68881 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
[2025-10-05T23:22:21.036+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-05T23:22:21.037+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-05T23:22:21.098+0000] {logging_mixin.py:151} INFO - ✅ Curado: 1/14 → s3://respaldo2/rag/chunks_curated/2025/22045_2025-10-03.ndjson
[2025-10-05T23:22:21.098+0000] {python.py:194} INFO - Done. Returned value was: {'processed_files': 14, 'written_files': ['rag/chunks_curated/2025/22032_2025-09-16.ndjson', 'rag/chunks_curated/2025/22033_2025-09-17.ndjson', 'rag/chunks_curated/2025/22034_2025-09-18.ndjson', 'rag/chunks_curated/2025/22035_2025-09-19.ndjson', 'rag/chunks_curated/2025/22036_2025-09-22.ndjson', 'rag/chunks_curated/2025/22037_2025-09-23.ndjson', 'rag/chunks_curated/2025/22038_2025-09-24.ndjson', 'rag/chunks_curated/2025/22039_2025-09-25.ndjson', 'rag/chunks_curated/2025/22040_2025-09-26.ndjson', 'rag/chunks_curated/2025/22041_2025-09-29.ndjson', 'rag/chunks_curated/2025/22042_2025-09-30.ndjson', 'rag/chunks_curated/2025/22043_2025-10-01.ndjson', 'rag/chunks_curated/2025/22044_2025-10-02.ndjson', 'rag/chunks_curated/2025/22045_2025-10-03.ndjson'], 'in_records': 14, 'out_records': 14}
[2025-10-05T23:22:21.114+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=flujo_RAG, task_id=guardrail_chunks, execution_date=20251005T231422, start_date=20251005T232034, end_date=20251005T232221
[2025-10-05T23:22:21.152+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-05T23:22:21.173+0000] {taskinstance.py:2776} INFO - 2 downstream tasks scheduled from follow-on schedule check
